### ISSUE TITLE
Rework the section regarding $id and $ref

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/understanding-json-schema#104]
The example of how to use `$id` with `$ref` is not how we would like people to do things.

https://json-schema.org/understanding-json-schema/structuring.html#using-id-with-ref

We should rework this to show the intended general use case, where you reference another file by it's `$id`, including relative URI resolutions.

It's possibly worth noting that you can use an `$id` in a subschema, but it's not advised because it makes things more complex.

Additionally, is the statement about no support for this true in terms of the python library?

@Julian ?

**Comment by Julian** [comment]
It definitely supports id+ref generally, but what that seems likely to be trying to say at the minute is the "location independent" references which aare indeed not supported yet (and are a pain to implement. But some day I guess it will have to happen).

**Comment by handrews** [comment]
@Julian would https://github.com/json-schema-org/json-schema-spec/issues/729 make this any easier or harder?

IIRC the problem was doing the pre-scan to find all of the `"$id": "#foo"` anchors, so changing that to `"$anchor": "foo"` would not really make that easier.

Although it **would** arguably make it less confusing: instead of being this weird _well... some `$id`s work and some don't_ situation, it would just be _`$anchor` is not supported_.  So that would seem to be a slight argument in favor of #729?  (Recall that I brought up putting it in draft-08 after all a couple of weeks ago).

**Comment by Julian** [comment]
I think #729 is a positive change (for the reasons you mentioned, so you've got my vote), but yeah doesn't help the key issue which is having to do two passes (or, having to do one, ahead of time pass).

The only thing I think that'd help that is having a designated section for location-independent refs so that you don't need 2 passes and can just know to always look there, but I think I remember you saying there are reasons that the way things are now is needed or convenient for authors, so yeah definitely not saying I have all the answers on that one.

**Comment by handrews** [comment]
We now have more clarity in the spec on [why you would want to use `$id` outside of a document root](http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.appendix.B.1), and have also split out the use case in this section of Understanding JSON Schema into the [$anchor keyword](http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.2.3), which should make all of this less confusing.

The section referenced by this bug should now talk about `$anchor`, and the rest of `$id`'s behavior should show up somewhere else (I don't know if it already does in the current book or if we'll need to add that).
