### ISSUE TITLE
PR build previews do not include PDF version

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/understanding-json-schema#155]
It's unclear if we wish to continue to support the PDF version of this resource, especially if we plan to merge it into the main JSON Schema site repo. However, should we decide we DO want to, or someone from the community is willing, there may be some useful informatio regarding how we might achive this in the following gist.

https://gist.github.com/ridem/5e1608e771f7cfc9798d33c72903fb35

This relates specifically to needing texlive available to the build processor, Netlify.

**Comment by jdesrosiers** [comment]
If it's a hassle, then it's not worth it. I wouldn't bother trying to get it working.

**Comment by jdesrosiers** [comment]
It turns out that the preview builds aren't working perfectly. The "Draft Specific" and "Language Specific" sections specifically don't render properly. Getting those issues working in local builds (#157) turned out to fix the pdf generation as well. I don't know how netlify works exactly but, what I figured out for #157 might be useful in getting those builds working properly.

For now, production deploy is going through Travis, so the minor rendering issues are not a big deal for deploy previews. But if we want to move off of Travis and use Netlify for production deployment, we'd have to solve the problem.

**Comment by benjagm** [comment]
With the release of the new JSON Schema website this issue is going to be closed as not planed.
