### ISSUE TITLE
Draft-6 is coming!

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/understanding-json-schema#62]
Hey Team!

Just wanted to let you know we're getting pretty close to finishing and releasing draft-6.
I don't know if you plan to continue maintaining this resource, but it's useful to me and many others.

Cheers

**Comment by embray** [comment]
Cool--is there some place to see an overview of what's changed?

**Comment by Relequestual** [comment]
You would want to look at the core, validation, and maybe hyperschema specification documents. They provide a chaneglog near the end http://json-schema.org/documentation.html - draft-6 is now published.

**Comment by augusthur** [comment]
In http://json-schema.org/draft-06/json-schema-migration-faq.html you have all the changes between draft-04 and draft-06.

**Comment by handrews** [comment]
@embray @augusthur draft-07 is coming!  :-D

The main differences from draft-06 will likely be:

* `if`/`then`/`else` keywords
* features from hyper-schema that are often used without hyper-schema are now in validation:
    * `readOnly` is now in the validation schema's metadata section
    * encoding data into JSON strings with `contentMediaType` and `contentEncoding` (formerly `media`, now an **optional** validation feature, like `format`)
* numerous additional / restored / clarified `format`s
    * `regex` restored (removing it was a bug)
    * `json-pointer` clarified, `relative-json-pointer` added
    * `iri`, `iri-reference`, `idn-hostname`, `idn-email` internationalized formats
* more detailed guidance on how to use annotation keywords (`title`, `description`, `default`, `examples`, `readOnly`)

There may also be something around marking things as deprecated, although this turns out to be unexpectedly complicated and controversial so it's not clear if it will make this draft or the next one.

The only mandatory new implementation requirement is `if`/`then`/`else`.

In addition, Hyper-Schema is getting a complete rewrite, although no features from draft-06 are being removed.  Naming is being made more consistent, numerous features are added, and clear implementation requirements are being specified, to enable creating a conformance test suite.

**Comment by handrews** [comment]
@embray what would be a good way to make progress on this?  I'm happy to help, but don't want to try to update everything at once and then find out that I've gotten the tone wrong or otherwise messed things up.

Additionally, how much information about draft-04 should be kept?  We're really trying to encourage folks to move up to draft-06 and draft-07, and even some of the larger projects such as OpenAPI are starting to move on that.

**Comment by handrews** [comment]
[draft-07](http://json-schema.org/documentation.html) has been published.

**Comment by lordrhodos** [comment]
would love to see updated contents for draft-07 here as well. Any news about if updating the books contents is plannend and will be maintained in the future?

**Comment by mdboom** [comment]
See #74 for an update to Draft 6.  It would be great to update to Draft 7, but Julian/jsonschema doesn't support that yet, and it would be great to continue to have the automatic verification of the examples.  Does anyone know the timeline for that?

**Comment by Relequestual** [comment]
@Julian ^^ ?

**Comment by Julian** [comment]
Support for Draft 7 is on a branch already, mostly complete IIRC. I can likely merge that in the next few days.

**Comment by Relequestual** [comment]
Awesome! Great work! =]

**Comment by Julian** [comment]
Still some kinks to work out (please lemme know if you find any!) but just pushed out a first draft 7 alpha release (v3.0.0a3).

**Comment by mdboom** [comment]
Thanks.  I'm going to close this, since the draft 6 content has been written and merged, and we have #79 to track the draft 7 work.
