### ISSUE TITLE
Dot metacharacter not recommended in regular expressions

### ISSUE THREAD

**Issue by jkieboom** [json-schema-org/understanding-json-schema#90]
In https://json-schema.org/understanding-json-schema/reference/regular_expressions.html#regular-expressions it is mentioned that use of `.` is not recommended in regular expressions. It specifically mentions python in this context, but to my knowledge `.` has been supported in regular python `re` since a very long time (e.g. python 2.5 has this). What's the reason use of `.` is not recommended?

**Comment by handrews** [comment]
That seems very strange.  `.` is one of the most basic features of regexps.  I've used Python for well over a decade without encountering any problems with it.  @mdboom do you have any idea where this came from?

**Comment by mdboom** [comment]
It comes from the recommendation in JSON Schema Validation Draft 4 that patterns SHOULD limit themselves to a subset of values: https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-3.3

The context here is that you want to write a regex that is portable across all JSON Schema engines you may encounter, and most of them that I've looked at simply pass regular expressions along directly to the language-specific regex engine (i.e. they don't do any parsing from a commonly agreed upon standard for regular expressions defined by the JSON schema spec, for example).  The recommendation not to use `.` is my own, and comes from the fact that it's use isn't recommended in the draft, and it's the sort of most common thing that one might think to use.

I haven't done an exhaustive survey of regular expression engines, but the [Wikipedia description of the meaning of the `.` character](https://en.wikipedia.org/wiki/Regular_expression#Standards) suggest to me it remains good to recommend against its use if the goal is broad compatibility and consistency of behavior:

"Matches any single character (many applications exclude newlines, and exactly which characters are considered newlines is flavor-, character-encoding-, and platform-specific, but it is safe to assume that the line feed character is included)."

**Comment by jkieboom** [comment]
For all practical purposes and languages, the `.` universally does not include newlines [1]. I also think that in the context of JSON, there isn't much ambiguity in terms of people using \n vs \r\n etc in JSON strings. To me the common use of `.` in many regular expressions and the fact that the differences between implementations doesn't seem practically relevant leads me to think that recommending against its use is an error. At most I would think this deserves a footnote in the documentation, not an outright omission.

[1] https://www.regular-expressions.info/dot.html

**Comment by mdboom** [comment]
The long list of gotchas on that page you link to leads me to the opposite conclusion, to be honest.  Differing levels of paranoia I suppose :)  I think perhaps it might be helpful to mention explicitly in the doc that the goal is to write regular expressions that will be maximally portable, hence the recommendation to avoid the `.` unless you know / control the implementations your schema will be used with.

When in doubt with this documentation I have tried to hew closely to the JSON schema spec, where `.` is not recommended.  @handrews : Do you recall the motivation for excluding `.` from the list of recommended operators in the draft (up to and including draft 8)?  Perhaps it wasn't very strong since even you were surprised by it? :)

**Comment by handrews** [comment]
@mdboom I see how you came to this conclusion, but I think it's really confusing to discourage one of the most fundamental syntax elements of regular expressions.  No one who had anything to do with writing that block on regexes is still associated with the project.  I have never given it a single conscious thought- I moved it over to core without even reading it, tbh.

I think @jkieboom is right that it should be more of a footnote than an exclusion.  The "long list of caveats" breaks down into a few categories:

* Notes about how to turn on a "match line breaks" option- these are irrelevant, as no one in their right mind randomly turns that on, and if they do that in a JSON Schema implementation they are in egregious violation of the spirit if not the letter of the spec.  And with ECMA, probably in violation of the letter as well.
* Commentary on the nature of line breaks across different operating systems and runtime environments.  These are universal concerns across any and all text processing.  The dot operator behaves correctly matching local behavior.  People who worry about the sort of interoperability will either know about this, or will be shooting themselves in the foot in far more situations than JSON Schema anyway.
* Examples of people egregiously misusing the whole concept.  To be blunt, putting a dot instead of something like `[/-.]` in for date separators is ridiculous, and anyone who does that deserves what they get.  And it's not remotely specific to JSON Schema.

The only thing here that even might be worth noting is that typical line break interoperability issues apply.  That would make sense to note in Understanding JSON Schema.  Although it has absolutely nothing to do with Python, I have no idea why there's a language-specific note for that.  It's, of course, up to you how deep you want to go into the topic.

For the spec, I'll probably add a one-line note about it, as it is an interoperability issue.  But it's more of a "JSON Schema doesn't fix this totally normal thing that happens everywhere" issue than a "you need to use regexes totally differently in the context of JSON Schema" issue.

**Comment by mdboom** [comment]
Ok.  You've convinced me.  See #91 for a proposed fix.
